name: Merge queue and try

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ "auto", "try", "try-linux", "try-mac", "try-windows", "try-wpt"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  build-mac:
    name: Build (macOS)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # TODO: Remove this step when the compatibility issue between mozjs and
      #       Homebrew's Python 3.10 formula (servo/rust-mozjs#559) is fixed
      - name: Select Python 3.9
        run: |
          brew install python@3.9
          cd $(dirname $(which python3.9))
          rm -f python3 pip3
          ln -s python3.9 python3
          ln -s pip3.9 pip3
      - name: Bootstrap
        run: |
          python3 -m pip install --upgrade pip virtualenv
          brew install "https://github.com/Homebrew/homebrew-core/blob/49a8667f0c1a6579fe887bc0fa1c0ce682eb01c8/Formula/gstreamer.rb"
          brew bundle install --verbose --no-upgrade --file=etc/taskcluster/macos/Brewfile
          brew bundle install --verbose --no-upgrade --file=etc/taskcluster/macos/Brewfile-build
          rm -rf /usr/local/etc/openssl
          rm -rf /usr/local/etc/openssl@1.1
          brew install openssl@1.1 gnu-tar
      - name: Release build
        run: |
          export OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include"
          export OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"
          export PKG_CONFIG_PATH="$(brew --prefix libffi)/lib/pkgconfig/"
          export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig/:$PKG_CONFIG_PATH"
          python3 ./mach build --release
      - name: Smoketest
        run: python3 ./mach smoketest
      - name: Unit tests
        run: python3 ./mach test-unit --release
      - name: Test package
        run: python3 ./mach package --release
      - name: Package smoketest
        run: ./etc/ci/macos_package_smoketest.sh target/release/servo-tech-demo.dmg
      - name: Package binary
        run: gtar -czf target.tar.gz target/release/servo target/release/*.dylib resources
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: release-binary-macos
          path: target.tar.gz

