name: Pull request
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: ["**"]

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Bootstrap Python
        run: python3 -m pip install --upgrade pip virtualenv
      - name: Bootstrap dependencies
        run: sudo apt update && python3 ./mach bootstrap
      - name: Tidy
        run: python3 ./mach test-tidy --no-progress --all
      - name: Release build
        run: python3 ./mach build --dev
      - name: Unit tests
        run: python3 ./mach test-unit --dev
      - name: Lockfile check
        run: ./etc/ci/lockfile_changed.sh
